# 5

In [2]:
import numpy as np

P = np.array([
    [1/3, 2/3],
    [1,   0  ]
])

for m in range(1, 6):
    Pm = np.linalg.matrix_power(P, m)
    print(f"P^{m} =\n{Pm}\n")
for m in range(2, 600):
    Pm = np.linalg.matrix_power(P, m)
    assert np.all(Pm > 0), f"P^{m} has a non-positive entry:\n{Pm}"


P^1 =
[[0.33333333 0.66666667]
 [1.         0.        ]]

P^2 =
[[0.77777778 0.22222222]
 [0.33333333 0.66666667]]

P^3 =
[[0.48148148 0.51851852]
 [0.77777778 0.22222222]]

P^4 =
[[0.67901235 0.32098765]
 [0.48148148 0.51851852]]

P^5 =
[[0.5473251  0.4526749 ]
 [0.67901235 0.32098765]]



In [12]:
Pms = [np.linalg.matrix_power(P, m) for m in range(0,30)]
for m in range(20,30):
    Pm = Pms[m]
    Pm_1 = Pms[m-1]
    print(f"P^{m} =\n{Pm}\n; Diff =\n{Pm - Pm_1}\n")

P^20 =
[[0.60012029 0.39987971]
 [0.59981956 0.40018044]]
; Diff =
[[ 0.00030073 -0.00030073]
 [-0.00045109  0.00045109]]

P^21 =
[[0.59991981 0.40008019]
 [0.60012029 0.39987971]]
; Diff =
[[-0.00020049  0.00020049]
 [ 0.00030073 -0.00030073]]

P^22 =
[[0.60005346 0.39994654]
 [0.59991981 0.40008019]]
; Diff =
[[ 0.00013366 -0.00013366]
 [-0.00020049  0.00020049]]

P^23 =
[[0.59996436 0.40003564]
 [0.60005346 0.39994654]]
; Diff =
[[-8.91047881e-05  8.91047881e-05]
 [ 1.33657182e-04 -1.33657182e-04]]

P^24 =
[[0.60002376 0.39997624]
 [0.59996436 0.40003564]]
; Diff =
[[ 5.94031921e-05 -5.94031921e-05]
 [-8.91047881e-05  8.91047881e-05]]

P^25 =
[[0.59998416 0.40001584]
 [0.60002376 0.39997624]]
; Diff =
[[-3.96021280e-05  3.96021280e-05]
 [ 5.94031921e-05 -5.94031921e-05]]

P^26 =
[[0.60001056 0.39998944]
 [0.59998416 0.40001584]]
; Diff =
[[ 2.64014187e-05 -2.64014187e-05]
 [-3.96021280e-05  3.96021280e-05]]

P^27 =
[[0.59999296 0.40000704]
 [0.60001056 0.39998944]]
; Diff =
[[-1.760

Numerically, $lim_{n-> \infty} P^n = [[0.6, 0.4], [0.6, 0.4]]$

To show irreducibility: a finite Markov chain is irreducible iff for every pair of states i,j ($i \neq j$), there exists some m such that $P^m_{i,j} > 0$. This indicates that there is transition between 2 (non-same) states. We have shown this above, where there is more than 1 positive non-diagonal element in each of P^m (for m ranging from 0 to 600).

The Markov chain is aperiodic because there exists $m \ge 1$ such that
$(P^m)_{ii} > 0$ for all states $i$. In particular, since $(P)_{11} > 0$ and $(P)_{11} < 1$,
the chain can return to state $1$ in one step, implying that the period
of state $1$ is equal to $1$. Because the chain is irreducible, all states
share the same period, and therefore the chain is aperiodic.
